"""add run owner

Revision ID: 050b89d5ff6a
Revises: a0505c0f9546
Create Date: 2026-09-28 21:17:19.596237

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '050b89d5ff6a'
down_revision = 'a0505c0f9546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_run_owner_id'), 'run', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'run', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'run', type_='foreignkey')
    op.drop_index(op.f('ix_run_owner_id'), table_name='run')
    op.drop_column('run', 'owner_id')
    # ### end Alembic commands ###
