"""cascade runs on user delete

Revision ID: 2fef5d2ca22e
Revises: 94e2821d22ff
Create Date: 2026-10-04 21:50:46.512051

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2fef5d2ca22e'
down_revision = '94e2821d22ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('run_owner_id_fkey'), 'run', type_='foreignkey')
    op.create_foreign_key(None, 'run', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'run', type_='foreignkey')
    op.create_foreign_key(op.f('run_owner_id_fkey'), 'run', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
