"""add run idempotency key

Revision ID: 94e2821d22ff
Revises: 050b89d5ff6a
Create Date: 2026-10-02 17:13:52.609932

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '94e2821d22ff'
down_revision = '050b89d5ff6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.create_unique_constraint('uq_run_owner_idempotency_key', 'run', ['owner_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_run_owner_idempotency_key', 'run', type_='unique')
    op.drop_column('run', 'idempotency_key')
    # ### end Alembic commands ###
