"""add run table

Revision ID: a0505c0f9546
Revises: fe56fa70289e
Create Date: 2026-09-28 12:41:26.175782

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a0505c0f9546'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run',
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('input', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run')
    # ### end Alembic commands ###
